spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/evtx
    username: evtx
    password: evtx
  jpa:
    hibernate:
      ddl-auto: validate   # schema é responsabilidade do Flyway, não do Hibernate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    com.evtx: DEBUG
    org.springframework.security: INFO

app:
  catalog:
    ticketmaster:
      api-key: "75qRvvwobHQPckVBi9GeQPdG6RJw6QEH"
